### ISSUE TITLE
TP2 Deadlines

### ISSUE THREAD

**Issue by Pinh0** [miguelriemoliveira/psr_21-22#12]
TP2 Deadline is the same as the TP1

![Screenshot_31](https://user-images.githubusercontent.com/72825341/139538627-784e904d-30bc-4a9c-a0ce-7e4230a782f8.jpg)
Image screenshot from the Apresentação da UC file on Elearning (30/10/2021).

**Comment by miguelriemoliveira** [comment]
Hi @Pinh0 ,

nice to see students already thinking about TP2 : - ).

I will correct it, thanks.

**Comment by miguelriemoliveira** [comment]
I corrected the pdf.
