### ISSUE TITLE
Project delivery

### ISSUE THREAD

**Issue by GabrieleMicheli** [miguelriemoliveira/psr_21-22#14]
Good morning,
How can we deliver the project?

**Comment by emanuelkrzyszton** [comment]
Does anyone know how should we provide the working code to Professor @miguelriemoliveira ? 
Please let us know, we miss that information 
Thank you!

**Comment by miguelriemoliveira** [comment]
Hi @emanuelkrzyszton ,

All groups should send me an email indicating the group number and the github repository in which the group is developing the code. That is the "delivery". During the practical class, you will present the project.
