### ISSUE TITLE
Aula 5 P1

### ISSUE THREAD

**Issue by Analtino2021** [miguelriemoliveira/psr_21-22#15]
Boa Tarde professor será possível disponibilizar a aula prática da turma P1

**Comment by miguelc3** [comment]
E a aula TP também, por favor

**Comment by miguelriemoliveira** [comment]
Boa tarde,

estou a fazer upload. 30 mins.

**Comment by miguelriemoliveira** [comment]
Já lá estão as aulas. Cumprimentos,
