### ISSUE TITLE
Are you speaking challenge 

### ISSUE THREAD

**Issue by josepedropinto-pt** [miguelriemoliveira/psr_21-22#16]
Good evening,

Regarding the "Are you speaking" exercise, it's cheating to import the python library "face_recognition" for starting point or it's part of the challenge to create from zero the algorithm?

**Comment by miguelriemoliveira** [comment]
Hi @josepedropinto-pt ,

its not cheating. You can use any library or functionality you can find. For example, opencv has a face detection part also.
