### ISSUE TITLE
Part 7 key duplication

### ISSUE THREAD

**Issue by joao-pm-santos96** [miguelriemoliveira/psr_21-22#19]
Hello!

Just a notice. On Part 7 (TP2) the key 'c' is mentioned that should be use for cleaning the canvas but, further down, is also the key for drawing a circle.

Is this intended or can we use other key for the circle (like 'e' for ellipse)?

**Comment by joao-pm-santos96** [comment]
Also, on the video, you say that when we click 'c' we define the center of the circle, yet what we see is that the first click defines the fist 'corner' position of the circle. What should we implement?

**Comment by joao-pm-santos96** [comment]
> Just a notice. On Part 7 (TP2) the key 'c' is mentioned that should be use for cleaning the canvas but, further down, is also the key for drawing a circle.

The same applies for 'r' and color red. Maybe 's' for square?

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,  you are right, just select the keys you think make more sense, about the circle, do it as you preffer also. Have a nice weekend.

**Comment by miguelriemoliveira** [comment]
Hi  @joao-pm-santos96 ,

updated the Parte07 to avoid conflict in the keys, following your suggestions. 

Thanks,
Miguel

**Comment by miguelriemoliveira** [comment]
Hi  @joao-pm-santos96 ,

updated the Parte07 to avoid conflict in the keys, following your suggestions. 

Thanks,
Miguel
