### ISSUE TITLE
TP2 - Advanced Functionality 2

### ISSUE THREAD

**Issue by manuelgitgomes** [miguelriemoliveira/psr_21-22#21]
On the description of the advanced functionality 2 it's not clear to me what it is meant with "imagens capturadas periódicamente pela camara". Show we change between the camera and the white canvas periodically? Or should we assign a button to change between them?

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

the idea is to have the video feed as background while you are painting. This should be activated with a button or a command line argument.

**Comment by manuelgitgomes** [comment]
Ok, thank you! Issue closed
