### ISSUE TITLE
TP2 - Advanced Functionality 2

### ISSUE THREAD

**Issue by RSiopa** [miguelriemoliveira/psr_21-22#22]
Good night professor,

In functionality 2 I am changing between the white board and the video stream when i click a specific key. If i change to the video stream, is it supposed to still have the drawings I made over the video?

Thank you.

**Comment by miguelriemoliveira** [comment]
Hi @RSiopa ,

yes, good idea.

**Comment by RSiopa** [comment]
Thank you for the answer!
