### ISSUE TITLE
 TP2 - Advanced Functionality 4

### ISSUE THREAD

**Issue by RSiopa** [miguelriemoliveira/psr_21-22#23]
Good night professor,

In functionality 4, are we supposed to use images as shown in the description of the functionality, or are we supposed to receive a colored picture, turn it into a black and white picture, divide it into sections (maybe with edge detection and an erode) and save the colors that the user should paint in functionality 5?

Thank you for your patience.

**Comment by miguelriemoliveira** [comment]
Hi @RSiopa 

the idea is that you have stored 2 or 3 images with all the information you need to paint. I will evaluate this from a user's perspective, meaning I do not care how you prepared the images for painting, I just want to see if they look nice and if the user experience of painting them is pleasant.

**Comment by RSiopa** [comment]
It seems I was over-complicating, thank you!
