### ISSUE TITLE
Commit to GitHub Issues

### ISSUE THREAD

**Issue by josepedropinto-pt** [miguelriemoliveira/psr_21-22#26]
Bom dia, 

Antes de alterar as pastas das aulas para o "catkin_ws" quando fazia commit os ficheiros apareciam subdivididos por pastas. Agora aparecem-me todos misturados e fica um bocado confuso. Existe alguma forma de resolver isto? Já pesquisei e não encontro nada.

Obrigado

![Screenshot from 2021-11-28 11-43-42](https://user-images.githubusercontent.com/93255728/143766383-93dfd434-39fb-4177-904e-61b01ab084b3.png)
.
![Screenshot from 2021-11-28 11-42-46](https://user-images.githubusercontent.com/93255728/143766389-0012ca79-659d-4d1f-9425-364d0b8ef708.png)

**Comment by miguelriemoliveira** [comment]
Olá @josepedropinto-pt ,

se se refere à segunda imagem o que está a ver não é a árvore do projeto mas a lista dos ficheiros alterados a serem enviados para o repositório git. Será essa a confusão ?

**Comment by josepedropinto-pt** [comment]
Olá,
Sim estou a referir-me à segunda imagem. Na segunda imagem esses ficheiros costumavam ficar organizados em subpastas.

**Comment by miguelriemoliveira** [comment]
Olá @josepedropinto-pt , 

e se escoher a árvore de projeto já não tem a vista que quer?

**Comment by josepedropinto-pt** [comment]
Okay já descobri, era aqui no "Group type" que estava como "repositório" e eu queria como "diretório"

Obrigado professor e desculpe

![Screenshot from 2021-11-28 22-53-04](https://user-images.githubusercontent.com/93255728/143789626-8ed8b588-e102-43c1-a7c1-567666c74244.png)

**Comment by miguelriemoliveira** [comment]
Ok, ainda bem.
