### ISSUE TITLE
Problema a importar o cão

### ISSUE THREAD

**Issue by JorgeFernandes-Git** [miguelriemoliveira/psr_21-22#27]
No ex8, quando mando correr o publicador dá erro no import do Dog, alguem tem este problema?

A mensagem aparece no terminal com o comando rosmsg show e já fiz o comando catkin_make. Ambus o cmakelist e package estão corretamente configurados. 

Agradeço desde já a ajuda

**Comment by JorgeFernandes-Git** [comment]
**Problema resolvido**. 

Tive de correr este comando na pasta src do package. Entretanto criei outro package e funciona também!

    source ~/catkin_ws/devel/setup.bash

**Comment by miguelriemoliveira** [comment]
Ok, ainda bem que resolveu. Esse comando de que fala está nas instruções de instalação do ROS. É importante cumprir todos os passos dos manuais.
