### ISSUE TITLE
rqt console doesn't show the messages properly

### ISSUE THREAD

**Issue by lucasrdalcol** [miguelriemoliveira/psr_21-22#29]
Hi Professor @miguelriemoliveira and @danifpdra, 

I am facing a problem with rqt console that doesn't show the messages properly. I am doing this [tutorial](http://wiki.ros.org/ROS/Tutorials/UsingRqtconsoleRoslaunch) from ROS website.
Furthermore, I searched on Google, and I've found people having the same issue but with no solution. https://answers.ros.org/question/300367/rqt_console-tool-doesnt-display-message/

The problem is that I open the rqt console, the rqt logger level and when I start the TurtleSim node, the rqt logger level recognizes it but the rqt console no and doesn't show the messages that is supposed to show according to the tutorial.

![image](https://user-images.githubusercontent.com/86158939/143859394-7a300a17-dbf1-4119-b2f2-d47780e103ec.png)

Can you help me?

**Comment by lucasrdalcol** [comment]
Suddenly it started to work, but I will maintain the issue a bit more to see if there is any solution for that because probably someone else is having the same problem.

**Comment by lucasrdalcol** [comment]
And it appears something like this when is not working:

![image](https://user-images.githubusercontent.com/86158939/143863297-a1476d41-01d7-40b7-9bae-b0fb74931fc1.png)

**Comment by miguelriemoliveira** [comment]
Hi @lucasrdalcol ,

lets do a zoom meeting for this, since I do not know how to solve it ...

**Comment by miguelriemoliveira** [comment]
Well, now its working?

**Comment by lucasrdalcol** [comment]
Hi @miguelriemoliveira, for now yes, but I will see if it continuous to work. If I have some problem with this, I reopen this issue.
