### ISSUE TITLE
ROS Installation

### ISSUE THREAD

**Issue by GabrieleMicheli** [miguelriemoliveira/psr_21-22#30]
Good evening,
I am installing ROS Noetic (I am late I know but I had many problems ...) following the tutorial on wiki: [](http://wiki.ros.org/noetic/Installation/Ubuntu) but I have a problem (see attachment) when I use the **sudo apt install ros-noetic-desktop-full command**. Have any of you had this problem? Before asking on Github I searched a lot of things on google but still couldn't solve the problem. Could you help me please?
![terminalError](https://user-images.githubusercontent.com/93253340/144293560-a7092c3a-57da-4431-ab26-ba3585754c71.png)

**Comment by miguelriemoliveira** [comment]
Hi @GabrieleMicheli ,

from here http://wiki.ros.org/noetic/Installation/Ubuntu, are you sure you did all the steps?

Note that step 1.3 is actually two commands to be inserted separately in the terminal.

Also, can you post the result of command 

`lsb_release -a`

on your computer?

**Comment by GabrieleMicheli** [comment]
Yes I'm sure and everything seems to work fine except point 1.4. Attached the terminal screen for the command `lsb_release -a` The only doubt I have left is that something may have been wrong in point 1.1 Configure your Ubuntu repositories but I can't figure out what.
![terminalScreen](https://user-images.githubusercontent.com/93253340/144319820-aeee4e41-3df7-4772-bf30-467703ce7037.png)

**Comment by miguelriemoliveira** [comment]
Hi @GabrieleMicheli ,

not sure what's happening. Lets try to fix it tomorrow in the practical class. If we cannot then we can schedule a zoom to look into it.

**Comment by GabrieleMicheli** [comment]
Thank you Professor!

**Comment by manuelgitgomes** [comment]
The link talked about is in [here](https://stackoverflow.com/questions/26571326/how-do-i-resolve-the-following-packages-have-unmet-dependencies).
