### ISSUE TITLE
Stresses com o ros

### ISSUE THREAD

**Issue by tiagomateus25** [miguelriemoliveira/psr_21-22#32]
Boa tarde professor, 
Estou com uns problemas que nao estou a conseguir resolver por mais que tente. No código por exemplo do publisher, quando tento dar import do rospy ele não o reconhece. O ex3 da aula 8 ainda assim funciona mas no exercicio 3_p3, quando tento fazer rosmsg, não deteta o ficheiro Dog.msg. 
Já tentei fazer varias vezes o catkin_create_pkg com as dependencias necessárias e nao esta a resultar, ja vi se era algum problema com a instalação do ros em si e tambem parece estar tudo em ordem. Tenho acompanhado os exercicios da aula mas nao os consigo por a correr e penso que seja por causa disto.

Cumprimentos,
Tiago Fonte N93225

![Screenshot from 2021-12-02 13-27-22](https://user-images.githubusercontent.com/92534397/144432060-048dfac4-beee-4638-8a98-ff3ace09b51f.png)

**Comment by miguelriemoliveira** [comment]
Olá @tiagomateus25 ,

veja o vídeo da aula P1 desta semana, que vou carregar para o youtube em breve.

Acho que tem lá a resposta.

Cumprimentos,
Miguel

**Comment by tiagomateus25** [comment]
Bom dia professor,

Ja consigo por os exercicios a correr, obrigado. Ainda assim, os imports aparecem me ainda como unresolved reference (sublinhados a vermelho), devo apenas ignorar esse erro?

**Comment by miguelriemoliveira** [comment]
Já viu o video?

Cumprimentos,
Miguel

**Comment by tiagomateus25** [comment]
Sim, realmente faltava me o source ~/catkin_ws/devel/setup.bash no .bashrc . Os codigos para ja correm, caso parem eu depois digo lhe na aula.

Cumprimentos,

Tiago Fonte N93225

**Comment by miguelriemoliveira** [comment]
Ok. Ainda bem.
