### ISSUE TITLE
Probelm with messages 

### ISSUE THREAD

**Issue by Analtino2021** [miguelriemoliveira/psr_21-22#33]
I'm taking classes to exercise and having a problem with the catkin_messages command because when I do catkin_make it runs all the files and some of them haven't created my message yet. like Simplebot_bringup and Simplebot_calibration which are the ones I'm having problems wit

![Catkin_problem1](https://user-images.githubusercontent.com/92738054/144710270-ca9cf841-e59b-4b8d-930d-e9d81c3fd1b3.png)
h.
![Catkin_problem2](https://user-images.githubusercontent.com/92738054/144710302-25cf57a5-6d0b-4656-bbd7-bd489b37a7ec.png)

**Comment by miguelriemoliveira** [comment]
Hi @Analtino2021 ,

this stuff about ATOM you should create an issue in the ATOM repository.

In any case I would say that simplebot calibration depends on the package atom calibration. Did you install it already?

https://github.com/lardemua/atom

**Comment by Analtino2021** [comment]
Solves
