### ISSUE TITLE
issue with custom msg

### ISSUE THREAD

**Issue by FelicianoSachilombo** [miguelriemoliveira/psr_21-22#34]
Boa tarde professor @miguelriemoliveira @danifpdra 
![issue](https://user-images.githubusercontent.com/92868202/144870136-7c9b1d5d-c6fb-49ec-b800-cb8d82903c4b.png)

Estive a refazer a aula/parte08, infelizmente não consigo criar o ros msg (exercício 4) mesmo seguindo os passos meticulosamente.

Executa sem erro quando corro o comando catkin_make mas não aparece nada quando corro o rosmsg list | grep Dog.

**Comment by miguelriemoliveira** [comment]
Quer fazer um zoom agora?

**Comment by FelicianoSachilombo** [comment]
Posso sim

**Comment by miguelriemoliveira** [comment]
ok, no zoom aula T de PSR ... até já.

**Comment by miguelriemoliveira** [comment]
Acho que o seu computador desligou. De qq forma já estava resolvido, certo?

**Comment by FelicianoSachilombo** [comment]
Desculpa professor, acabei por ficar sem carga.

**Comment by miguelriemoliveira** [comment]
Sem problema. Agora não posso mais, mas acho que já estava tudo bem, certo?

**Comment by FelicianoSachilombo** [comment]
Estava sim. 
Obrigado

**Comment by rodrigof1998** [comment]
Boa noite, estou com o mesmo problema. Qual foi a solução encontrada para o mesmo? @FelicianoSachilombo @miguelriemoliveira

**Comment by miguelriemoliveira** [comment]
Olá @rodrigof1998 ,

já tentou as soluções de que falamos em cima?

**Comment by rodrigof1998** [comment]
Bom dia, ontem tentei e não funcionou. Hoje de manhã apaguei a pasta do github de psr_21-22 do stor do meu catkin_ws e voltei a fazer tudo e corri também o comando que o stor disse em cima e já funcionou. Penso que era um conflito por haver demasiadas mensagens dog no meu sistema.

**Comment by miguelriemoliveira** [comment]
Ok. Está resolvido.

**Comment by rodrigof1998** [comment]
Boa tarde, sim está. 
Agora o problema é que o pycharm não consegue importar a mensagem Dog como dá para ver no print. 
![image](https://user-images.githubusercontent.com/92920806/148081996-19061e14-3dcd-40c4-83a6-f8c64cc8e7eb.png)

**Comment by miguelriemoliveira** [comment]
Olá @rodrigof1998 ,

pode ser por causa de várias coisas ... sugiro que reveja a aula onde se estão a criar mensagens custom. Já a viu? Seguiu o procedimento que lá é explicado?

Consegue consultar a mensagem usando o 

   `rosmsg list | grep Dog`

**Comment by rodrigof1998** [comment]
Olá professor, 
Sim eu consigo consultar a mensagem com o comando
`rosmsg list | grep Dog` 
mas só depois de executar o comando 
`source ~/catkin_ws/devel/setup.bash`
A questão é que se eu for executar o código do subcritor a seguir ele dá erro pois diz que não consegue importar o Dog
Eu já refiz o procedimento que o stor fez na aula e nada resultou. Estive umas boas horas a pesquisar na net varias possiveis soluções. O único método que resulta é mesmo se eu executar os comandos todos juntos como a seguir.
`source ~/catkin_ws/devel/setup.bash && clear && ./publisher.py `
Está é a única forma que consegui que funcionasse. Porquê? Não sei, mas o que interessa é que funciona! 
Fica aqui a dica para quem acontecer o mesmo. 
Obrigado pela ajuda!

**Comment by miguelriemoliveira** [comment]
Olá @rodrigof1998 ,

obrigado pela explicação detalhada, e por tentar ajudar os colegas. Assim com detalhes é mais fácil ajudá-lo.

O que se passa é que lhe falta a linha 

`source ~/catkin_ws/devel/setup.bash`

no ficheiro de inicialização do terminal, o ficheiro **.bashrc**

Veja o ponto 1.5 aqui 

http://wiki.ros.org/noetic/Installation/Ubuntu

**Comment by rodrigof1998** [comment]
Boa noite, 
Eu quando pesquisei na net esse foi um dos problemas que poderia ser mas por acaso eu fui verificar e tenho essa linha de código no ficheiro .bashrc. 
O pycharm agora já reconhece o import quando comecei a fazer o 
`source ~/catkin_ws/devel/setup.bash && clear && ./publisher.py`
Vou tentar fazer um reset ao pycharm e reiniciar o pc para ver se resolve.
