### ISSUE TITLE
ROS_TF2

### ISSUE THREAD

**Issue by josepedropinto-pt** [miguelriemoliveira/psr_21-22#37]
Bom dia Professor,

Uma questão em relação ao exercicio 4 para retirar as distância entre mercurio e a lua. 
O ROS faz automaticamente a gestão e calculo entre transformações dependentes ou temos que fazer isso em código?
Basicamente quero saber se posso diretamente calcular a distância euclidiana com o que tiro da linha 26. Ou se tenha que usar o que retiro das linhas 22-24 e somar a distancia "terra-lua" com a "sol-terra" e substrair à "sol-mercurio".

![Screenshot from 2021-12-12 12-07-00](https://user-images.githubusercontent.com/93255728/145711647-f7535cd5-8d23-4a72-aceb-77bda3832d4e.png)

**Comment by miguelriemoliveira** [comment]
Olá José,

Consegue pedir ao ros para o fazer. É uma das grandes vantagens do ros tf.
Você viu o video no primeiro link? Acho que falo disso lá.

Cumprimentos,
Miguel

**Comment by josepedropinto-pt** [comment]
Olá Professor,

Okay ótimo assim fica mais fácil.
Vi, mas como o professor também falava lá naquela multiplicação do "path" de transformações fiquei na dúvida. 

Obrigado
José Pedro
