### ISSUE TITLE
Intalação urdfdom_py

### ISSUE THREAD

**Issue by miguelc3** [miguelriemoliveira/psr_21-22#40]
![Screenshot from 2021-12-20 19-13-56](https://user-images.githubusercontent.com/92784719/146820376-396b9064-c35e-4741-8fcf-1ea27ed78be1.png)

No exercicio 6 da parte 11, ao tentar correr o 'sudo apt-get install ros-noetic-urdfdom-py' no terminal para fazer a instalação do pacote aparece sempre uma mensagem a dizer que não é possível localizar, há alguma coisa que tenho de fazer antes, ou que estou a fazer mal?

Obrigado,
mcp, 88731

**Comment by miguelriemoliveira** [comment]
Olá @miguelc3 ,

estranho. Acho que está a fazer tudo bem. No meu computador o comando funciona. Tem a certeza que configurou corretamente os repositórios do ROS? Fez os passos 1.1 a 1.4 deste manual?

http://wiki.ros.org/noetic/Installation/Ubuntu

**Comment by miguelc3** [comment]
Já consegui, era um problema com o passo 1.2 da instalação.
Obrigado!
