### ISSUE TITLE
Problemas de commit e push

### ISSUE THREAD

**Issue by tiagomateus25** [miguelriemoliveira/psr_21-22#41]
Boa noite professor,

Estive a acabar os exercícios das partes 10 e 11 e quando quis fazer commit e push para o meu repositório, aparece me este erro. Já tentei como arranjar uma solução para isto mas sem sucesso. Se me pudesse ajudar ficaria agradecido. 

Cumprimentos,

Tiago Fonte N93225

![Screenshot from 2021-12-30 01-00-21](https://user-images.githubusercontent.com/92534397/147713628-5532f4c6-2cce-4c55-a5f6-c0f6ebe1cde7.png)

**Comment by miguelriemoliveira** [comment]
Olá @tiagomateus25 ,

não consigo ler muito bem a imagem. É melhor fazer copy pasta do código.

Já fez uma busca no google? Algum resultado?

**Comment by tiagomateus25** [comment]
Sim e usei a solução lá dos foruns e não ajudou muito. No entanto, ja consegui resolver o problema.

**Comment by miguelriemoliveira** [comment]
Olá @tiagomateus25 ,

ainda bem que conseguiu resolver. Uma sugestão, use esta pergunta não só para o ajudar a si, mas também aos outros colegas.
Isto faz-se respondendo à própria pergunta quando encontramos a solução. Repare que se alguém tiver o mesmo problema que você, vai ler os posts e dizer:

> Sim e usei a solução lá dos foruns e não ajudou muito. 

Qual solução? Em que link?

> No entanto, ja consegui resolver o problema.

Como?

Bom ano,
Miguel
