### ISSUE TITLE
Robô parado em relação ao grid do Rviz

### ISSUE THREAD

**Issue by josepedropinto-pt** [miguelriemoliveira/psr_21-22#49]
Bom dia Professor,

Desde que coloquei o launch file para o gmapping o meu robô no Rviz não mexe, ou seja, tudo o resto ( mapa e nuvem de pontos) mexe em relação ao robô mas ele está sempre fixo no mesmo ponto. Alguma ideia do que pode ter causado isto e de como resolver?

![Screenshot from 2022-01-15 11-23-35](https://user-images.githubusercontent.com/93255728/149620174-483ac194-9c94-47dc-a00a-074a728a4438.png)

![Screenshot from 2022-01-15 11-23-12](https://user-images.githubusercontent.com/93255728/149620196-56fc1b34-7a34-4dae-90df-50d3d927fb75.png)

Obrigado

**Comment by miguelriemoliveira** [comment]
Olá José,

Veja a opção fixed frame do rviz.

**Comment by josepedropinto-pt** [comment]
Olá Professor,

Já tentei alterar isso e nenhuma funciona, mas era suposto funcionar com o "base_footprint" e também não dá.

**Comment by miguelriemoliveira** [comment]
Estranho. Com o base_footprint  como fixed frame não devia ver o robô a mexer. Apenas o mundo à volta do robô.

Mas com o p_jpedro/odom devia funcionar ... de certeza que não dá?

**Comment by josepedropinto-pt** [comment]
Okay descobri o problema, o meu "grid" estava com o "base_footprint" e não com a opção "fixed_frame" para ir buscar o escolhido nas "global_options". Devo ter alterado sem querer. Anyways está resolvido

**Comment by josepedropinto-pt** [comment]
Obrigado Professor

**Comment by miguelriemoliveira** [comment]
Ok, fixe.
