### ISSUE TITLE
gmapping installation

### ISSUE THREAD

**Issue by GabrieleMicheli** [miguelriemoliveira/psr_21-22#50]
Good afternoon,
I am trying to install gmapping using this command: **sudo apt-get install ros-noetic-gmapping** but it returns this error: **E: Unable to locate package ros-noetic-gmapping**
I tried to find a solution online but I still haven't solved it yet, has anyone had the same problem and was able to fix it?

![gmappingInstallation](https://user-images.githubusercontent.com/93253340/149665444-e05d6a7a-6111-47df-8598-3cf7d7787a30.png)

**Comment by miguelriemoliveira** [comment]
Hi @GabrieleMicheli ,

Strange. It worked for me.

Did you 

sudo apt-get update 

first?

Di you configure the ros repos correctly as in 1.2, 1.3 and 1.4?

http://wiki.ros.org/noetic/Installation/Ubuntu

You can try to use from github, but it would be better to use sudo apt-get install as discussed above

https://answers.ros.org/question/224502/slam_gmapping-installation/

**Comment by GabrieleMicheli** [comment]
Thanks professor @miguelriemoliveira, I solved the problem with your advice!

![gmappingInstallation](https://user-images.githubusercontent.com/93253340/149918639-c3fce249-5d45-4001-9437-f036fdff7fde.png)

**Comment by miguelriemoliveira** [comment]
Great. Please close the issue when solved.
