### ISSUE TITLE
Problemas a alterar cor do robô no rviz e no gazebo

### ISSUE THREAD

**Issue by davidgermanorodrigues** [miguelriemoliveira/psr_21-22#56]
Boa noite Professor Miguel,

Estava acompanhar a gravação da aula prática 13 e em certo ponto quando tentei lançar o meu bringup.launch surgiu-me o seguinte erro:

(...)

ROS_MASTER_URI=http://localhost:11311

process[p_drodrigues/robot_state_publisher-1]: started with pid [5194]
process[p_drodrigues/p_drodrigues/spawn_urdf-2]: started with pid [5195]
process[rviz-3]: started with pid [5197]
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/gazebo_ros/spawn_model", line 239, in <module>
    exit_code = sm.run()
  File "/opt/ros/noetic/lib/gazebo_ros/spawn_model", line 132, in run
    model_xml = rospy.get_param(self.args.param)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 467, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 123, in __getitem__
    raise KeyError(key)
KeyError: 'robot_description'
[p_drodrigues/p_drodrigues/spawn_urdf-2] process has died [pid 5195, exit code 1, cmd /opt/ros/noetic/lib/gazebo_ros/spawn_model -urdf -model p_drodrigues -x 0.0 -y -1.5 -z 0.0 -param robot_description __name:=spawn_urdf __log:=/home/germano/.ros/log/4a5fdf0e-822f-11ec-b995-71ffa88c47cc/p_drodrigues-p_drodrigues-spawn_urdf-2.log].
log file: /home/germano/.ros/log/4a5fdf0e-822f-11ec-b995-71ffa88c47cc/p_drodrigues-p_drodrigues-spawn_urdf-2*.log

**Comment by miguelriemoliveira** [comment]
Olá  @davidgermanorodrigues,

spawn_model -urdf -model p_drodrigues -x 0.0 -y -1.5 -z 0.0 -param robot_description

devia ser 

spawn_model -urdf -model p_drodrigues -x 0.0 -y -1.5 -z 0.0 -param $(arg player_name)/robot_description

**Comment by davidgermanorodrigues** [comment]
Entretanto já resolvi o problema.
Obrigado pela ajuda, professor.

**Comment by miguelriemoliveira** [comment]
olá @davidgermanorodrigues ,

Como resolveu? Se colocar aqui a resolução ajuda os colegas.

**Comment by davidgermanorodrigues** [comment]
Boa noite Professor Miguel,

Foi apenas uma distração minha.
Tinha-me esquecido de comentar o group ns="p_drodrigues" que se encontra na linha 9.

![2022-02-02_22-09](https://user-images.githubusercontent.com/92893270/152246713-e4851633-bd36-4e1a-8b7d-1276e8386ae7.png)

**Comment by miguelriemoliveira** [comment]
Ok.
