### ISSUE TITLE
Error: Type <class 'geometry_msgs.msg._PoseStamped.PoseStamped'> if not loaded or supported

### ISSUE THREAD

**Issue by MartinRivadeneira** [miguelriemoliveira/psr_21-22#57]
Good afternoon,

I was trying to subscribe the topic '/move_base_simple/goal' that sends a message that is geometry_msgs.msg - PoseStamped. Then I tried to transform the reception message into a new target frame, but then is would give an error that says that the type "geometry_msgs.msg._PoseStamped.PoseStamped" is not supported. 

I don't understand why it is coverting the type from "PoseStamped" to "_PoseStamped.PoseStamped".

The reading of the message is actually correct, I can print it and see that everything is okay, but when I try to do the transformation he just doesn't recognize the type of the message.

Thanks for your help!

Martin

**Comment by MartinRivadeneira** [comment]
@miguelriemoliveira

**Comment by miguelriemoliveira** [comment]
Hi @MartinRivadeneira ,

give me more details please.

Post the portion of the code and the terminal output with the full error.

**Comment by MartinRivadeneira** [comment]
So the subscription is:
rospy.Subscriber('/move_base_simple/goal', PoseStamped, GoalReceivedCallback)

and the callback function is defined by:
    
    def GoalReceivedCallback(msg):
    
    
        print('New Goal Received')
        target_frame = name + '/odom'
        print('The new target_frame is: ' + target_frame)
    
        goal = tf_buffer.transform(msg, target_frame, rospy.Duration(1))
        rospy.logwarn('Setting new goal')

![image](https://user-images.githubusercontent.com/92629573/151861282-f2703c22-59e0-4fed-a6d1-97e06d0ff623.png)

**Comment by MartinRivadeneira** [comment]
Hi @miguelriemoliveira,

It actually worked! Thank you!

**Comment by miguelriemoliveira** [comment]
> It actually worked!

You sound surprised ...that's the confidence you have in me right?

**Comment by MartinRivadeneira** [comment]
It's because I've been fighting this problem for a few days now and you solved in a few hours... it looks I don't understand anything about ROS ...     D:

**Comment by miguelriemoliveira** [comment]
Well, this was a tricky one.
