### ISSUE TITLE
Problem with topic /move_base_simple/goal

### ISSUE THREAD

**Issue by miguelc3** [miguelriemoliveira/psr_21-22#61]
I was re-testing the exercise of getting the robot to move to a target in the rviz but the code was not working. Then I realized it was because the code was not entering the 'goalReceivedCallback' function, so I did a ' rostopic echo /move_base_simple/goal' and when I set a goal no information appears in the terminal. Am I doing something wrong?
![Screenshot from 2022-02-10 09-36-17](https://user-images.githubusercontent.com/92784719/153381431-3b9d9636-6500-469c-ba85-1a6649de1284.png)
?

**Comment by miguelc3** [comment]
I figured out what was wrong, by doing a 'rostopic list' I saw that my /base_move_simple/goal' was actually as 'p_mpereira/p_mpereira/move_base_simple/goal'. I had one 'remap' in the 'visualize.launch' file that should not be there.

**Comment by miguelriemoliveira** [comment]
Great!
