### ISSUE TITLE
Sensor types for detection 

### ISSUE THREAD

**Issue by joao-pm-santos96** [miguelriemoliveira/psr_21-22#63]
Hello @miguelriemoliveira, @danifpdra,

what sensors can we use on the robots for TP3, for the detection of the other robots? 
Or are we free to chose whatever we want?

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,

yes you are free to choose.

**Comment by miguelriemoliveira** [comment]
... just try to be realistic about it ... for example, it does not make sense to put a camera with z=30 looking downwards. I did that and it is great for doing the AI, but unrealistic.

**Comment by joao-pm-santos96** [comment]
Didn't even thought of that... thank you for the inside tip! ;)
(No worry, we will keep it real)

**Comment by miguelriemoliveira** [comment]
sure, each robot with 20+ cameras ... very real : - )
