### ISSUE TITLE
Can RViz be associated with a namespace?

### ISSUE THREAD

**Issue by joao-pm-santos96** [miguelriemoliveira/psr_21-22#65]
Hi @miguelriemoliveira , @danifpdra 

Can RViz be associated with a namespace? That is, every topic for each robot (for example, red1) is inside a given namespace. But can this namespace be like an argument?

As an example, lets say that I make a wonderful RViz configuration using the red1 topics. If I want to use that same configuration, but with the green3 robot, the only way to do it is to change all topics from red1 to green3?

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,

I do not know of a simple way. I did it in ATOM but in a more complex way.

The mechanism there was to have template  of a .rviz file such as 

https://github.com/lardemua/atom/blob/noetic-devel/atom_calibration/templates/config.rviz

which is then populated using jinja. Here's an example:

https://github.com/lardemua/atom/blob/35325162894cbbf8444ae8418f03654ce4bd3b1c/atom_calibration/scripts/configure_calibration_pkg#L422-L489

I am not sure you should go down this path ... better to create one rviz config file for each robot.
