### ISSUE TITLE
game_bringup.launch file not working

### ISSUE THREAD

**Issue by GabrieleMicheli** [miguelriemoliveira/psr_21-22#66]
Good afternoon Professor @miguelriemoliveira,
I have a little problem launching the **game_bringup.launch** file. I run gazebo and it's working fine but after, launching the **game_bringup** file the terminal returns this error:

![image](https://user-images.githubusercontent.com/93253340/154500673-4791d54d-a4b0-4e84-a35a-edef53070067.png)

The program is working for my groupmates and it worked also before today. The only thing that I could have done is update Ubuntu and nothing more.

**Comment by miguelriemoliveira** [comment]
well, updating Ubuntu is the worst you can do! Do you know that the definition of an Ubuntu update is that it must brake something?

Post your xacro file so I can take a look please.

**Comment by GabrieleMicheli** [comment]
`<?xml version="1.0" ?>
<robot name="team_hunt_player" xmlns:xacro="http://ros.org/wiki/xacro">

  
  <xacro:arg name="player_name"  default="p_randomName"/>
  <xacro:arg name="player_color"  default="Red"/>

  
  <xacro:property name="player_name" value="$(arg player_name)"/>
  <xacro:property name="player_color" value="$(arg player_color)"/>

  
  <xacro:include filename="$(find p_group8_description)/urdf/properties.xacro"/>
  <xacro:include filename="$(find p_group8_description)/urdf/p_randomName.gazebo.xacro"/>

  
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/bases/waffle_pi_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>

      <material name="$(arg player_color)"/>
    </visual>

    <collision>
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="0.266 0.266 0.094"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.3729096e+00"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
               iyy="8.6195418e-03" iyz="-3.5422299e-06"
               izz="1.4612727e-02" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Yellow"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Yellow"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.177 -0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.177 0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_left_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.064 0 0.122" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.073 -0.011 0.584" rpy="0 0.45 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <collision>
      <origin xyz="0.005 0.011 0.013" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.030 0.027"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="0.003 0.011 0.009" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

</robot>`

**Comment by danifpdra** [comment]
hi @miguelriemoliveira and @GabrieleMicheli this problem was also happening in the new installed LAR computer

**Comment by PedroRibeiro37** [comment]
@GabrieleMicheli Ja tentaste apagar o ${property} e o $(arg argument) que estão comentados nas primeiras linhas ? A mim resultou

**Comment by GabrieleMicheli** [comment]
@PedroRibeiro37 I tried to translate your advice in english but sincerely I don't understand exactly what you mean? Could you repeat please? Google translation: "Have you tried deleting the ${property} and $(arg argument) that are commented out in the first lines? it resulted to me".

@miguelriemoliveira sure, here the link: [https://github.com/GabrieleMicheli/PSR_A3](url)

**Comment by PedroRibeiro37** [comment]
Yeah,yesterday i created a similar issue here and one of the students sugested me to remove that same expression,${property} and $(arg argument) that are commented (line 3 and 6).I dont know why but my xacro gets confused even commented.So i did it and it worked for me. Try to remove those expressions and try to run again.

**Comment by GabrieleMicheli** [comment]
@PedroRibeiro37 thank you so much, I fixed the problem just deleting the comment lines. 

One last question and after I'll close the issue, did you find an explanation for what happened? Because sincerely I don't understand...

**Comment by PedroRibeiro37** [comment]
No, i have no idea why this happen...Don´t make any sense but it works if deleted so... Maybe the teacher knows something about it ? @miguelriemoliveira

**Comment by miguelriemoliveira** [comment]
Hi @PedroRibeiro37 ,

thanks for helping out @GabrieleMicheli . I also have no idea why this occurs. Actually, me and @danifpdra were having problems in another system because of this and could not find a solution. So thank you for helping.

@danifpdra , can you confirm this solution solves our issues in larcc?

**Comment by miguelriemoliveira** [comment]
just one thing I am failing to understand: @GabrieleMicheli the xacro you posted does not have comments with the patterns @PedroRibeiro37 talked about. What exactly did you comment?

**Comment by GabrieleMicheli** [comment]
I changed the file from:
```
<?xml version="1.0" ?>
<robot name="team_hunt_player" xmlns:xacro="http://ros.org/wiki/xacro">

  <!--  Arguments - arguments are used as: $(arg argument) -->
  <xacro:arg name="player_name"  default="p_randomName"/>
  <xacro:arg name="player_color"  default="Red"/>

  <!-- Copying arguments to properties so that they are visible in the included xacros - properties are used as ${property} -->
  <xacro:property name="player_name" value="$(arg player_name)"/>
  <xacro:property name="player_color" value="$(arg player_color)"/>

  <!-- Including other xacro files -->
  <xacro:include filename="$(find p_group8_description)/urdf/properties.xacro"/>
  <xacro:include filename="$(find p_group8_description)/urdf/p_randomName.gazebo.xacro"/>
```
to:
```
<?xml version="1.0" ?>
<robot name="team_hunt_player" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="player_name"  default="p_randomName"/>
  <xacro:arg name="player_color"  default="Red"/>

  <xacro:property name="player_name" value="$(arg player_name)"/>
  <xacro:property name="player_color" value="$(arg player_color)"/>

  <!-- Including other xacro files -->
  <xacro:include filename="$(find p_group8_description)/urdf/properties.xacro"/>
  <xacro:include filename="$(find p_group8_description)/urdf/p_randomName.gazebo.xacro"/>
```
Deleting the two lines of comments:
`<!--  Arguments - arguments are used as: $(arg argument) -->`
 and
`<!-- Copying arguments to properties so that they are visible in the included xacros - properties are used as ${property} -->`

**Comment by miguelriemoliveira** [comment]
Thanks. Now I see it.
