### ISSUE TITLE
Adicionar texto no gazebo

### ISSUE THREAD

**Issue by Te1moFernandes** [miguelriemoliveira/psr_21-22#70]
Boa noite, @miguelriemoliveira @danifpdra 
Há alguma forma de legendar os robôs no gazebo? Ao pesquisar apenas encontro plugins que não funcionam.

**Comment by miguelriemoliveira** [comment]
Olá @Te1moFernandes , bom dia,

veja este script

https://github.com/miguelriemoliveira/psr_21-22/blob/main/TeamHunt/th_referee/src/set_player_names

**Comment by Te1moFernandes** [comment]
Obrigado professor 🗡️
