### ISSUE TITLE
TF sync issue

### ISSUE THREAD

**Issue by joao-pm-santos96** [miguelriemoliveira/psr_21-22#71]
Hi @miguelriemoliveira , @danifpdra 

He are trying to transform a pose between to existing and connect frames. Yet, the following error always occurs.

```tf2.ExtrapolationException: Lookup would require extrapolation 0.003000000s into the past.  Requested time 1126.316000000 but the earliest data is at time 1126.319000000, when looking up transform from frame [red1/map] to frame [red1/camera_rgb_optical_frame]```

It's just 3ms... do you know why this small difference is such a big issue?

@Pinh0 @GoncaloPeixinho @FelicianoSachilombo

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 ,

where are you initializing the tf listener? Is it inside a class method?

**Comment by joao-pm-santos96** [comment]
Hello,

It is in the class __init__ method.

**Comment by miguelriemoliveira** [comment]
Show me the line ...

**Comment by joao-pm-santos96** [comment]
Hi.

I think your fist commented actually solved it. We were using tf but in the classes you used tf2_ros (with an explicit buffer)

After following the tutorial, it is now working.

https://answers.ros.org/question/222306/transform-a-pose-to-another-frame-with-tf2-in-python/

Thanks!

**Comment by miguelriemoliveira** [comment]
OK, great.
