### ISSUE TITLE
Lidar values fused with cameras

### ISSUE THREAD

**Issue by Sarxell** [miguelriemoliveira/psr_21-22#75]
Hi @miguelriemoliveira ,

I have a problem about fusing the values of the lidar, I already checked the extrinsic and intrinsic camera parameters and they seem right. The problem is that I see the front values of the lidar in the image perfectly, but the back values also appear in the front image and vice-versa. I already took out one of the cameras but the problem stays. 

Does the professor have an idea to what might be? Because the front values are correct and the back too, but they appear in both images even when one is completely commented. That must be from the matrix but the matrix gives the correct values, maybe I can't transform all lidar points to both images?

Best regards, Sara

**Comment by Sarxell** [comment]
So, I created to different arrays of points, one for the back and other for the front, depending from the x and y value of the transformed laser point and it worked!

**Comment by miguelriemoliveira** [comment]
Nice!
